### ISSUE TITLE
cannot import build_centernet

### ISSUE THREAD

**Issue by interactivetech** [gau-nernst/centernet-lightning#2]
Thanks for making this library! I am unable to import build_centernet because the following code is missing from centernet.py
```
def build_centernet(config):
    if isinstance(config, str):
        config = load_config(config)
        config = config["model"]
    
    if "load_from_checkpoint" in config:
        model = CenterNet.load_from_checkpoint(config["load_from_checkpoint"], strict=False, **config)
    else:
        model = CenterNet(**config)
    return model
```

Could you add the code back so users can build the models? Thanks in advance :)

**Comment by gau-nernst** [comment]
Hello!

This library is not actively maintained anymore. I was doing a major refactoring but it never finished 🤣 . The new model is supposed to use Lightning CLI to automate the config file, but there are many limitations to Lightning CLI that I think I might remove Lightning CLI all together. You can still create a model directly by passing the appropriate arguments.

To use the old way, you can go back to the commit d9682de1 before the refactoring.

**Comment by interactivetech** [comment]
Thanks for the response! I will test the [d9682de](https://github.com/gau-nernst/centernet-lightning/commit/d9682de11cc2a7b6d86e5adc459d7e26404be1d3) branch now. Is it also possible to share any weights trained on that branch to ensure that training will work correctly?

**Comment by gau-nernst** [comment]
Unfortunately I don't keep any trained weights from the old branch

**Comment by interactivetech** [comment]
@gau-nernst I created a colab notebook ([link](https://colab.research.google.com/drive/1EhptEOmZU8tzHyhA7eIlKlxB8H1zG27b?usp=sharing)) that pulls the github repo from the specified [commit](https://github.com/gau-nernst/centernet-lightning/commit/d9682de11cc2a7b6d86e5adc459d7e26404be1d3), and I train a model from the default config `base_resnet34.yaml` for several epochs. When I run predictions from a trained checkpoint, the model seems to predict random boxes with class 0, and never seems to learn. Is there something I am missing to train a model using your repo?

**Comment by gau-nernst** [comment]
From what I see, you used SGD optimizer? You can try AdamW instead. From my experience, CenterNet is hard to converge with SGD. AdamW helps tremendously.

**Comment by interactivetech** [comment]
@gau-nernst reran training with AdamW and the model is now converging! Its interesting that the loss decreases, but the models prediction is soo poor using SGD. For future users, here are the AdamW settings I used. 
```
  optimizer:           # mmdetection
    name: AdamW          # any optimizers from torch.optim
    params:
      lr: 0.0005
      weight_decay: 0.0001
```
I wonder if the issue with SGD was the learning rate was too high?

**Comment by gau-nernst** [comment]
Glad that it works for you now!

SGD naturally requires higher learning rate than AdamW, since AdamW is an adaptive learning rate method. I have also tried tuning SGD learning rate but it was no success.

**Comment by javalier** [comment]
> @gau-nernst我创建了一个 colab 笔记本（[链接](https://colab.research.google.com/drive/1EhptEOmZU8tzHyhA7eIlKlxB8H1zG27b?usp=sharing)），它从指定的[提交](https://github.com/gau-nernst/centernet-lightning/commit/d9682de11cc2a7b6d86e5adc459d7e26404be1d3)中提取 github 存储库，并且我从默认配置`base_resnet34.yaml`中训练了一个模型几个 epoch。当我从经过训练的检查点运行预测时，该模型似乎预测了 0 类的随机框，并且似乎永远不会学习。使用您的存储库训练模型时我缺少什么吗？

**i have tested your colab,but i met these problems,how can you train succesfully?,the error is:**
[ ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/data.py) ]

**And I try this command "!python train.py --config "configs/coco_resnet34.yaml"",the error is :**
[
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/data.py)
]
