### ISSUE TITLE
some questions befor using

### ISSUE THREAD

**Issue by javalier** [gau-nernst/centernet-lightning#4]
I have some questions about compatibility, can the model trained with this project, such as adding the fpn module, be able to do map testing in the original centernet? The exported onnx model, whether it will encounter the problem of not recognizing some layers when converting to tensorrt, as well as version compatibility issues. In addition to that, whether the project will provide test map code, I saw the relevant test code in the project, but did not know how to use it. Sincerely look forward to your reply, I am a beginner, there are many things I don't know, thank you again for your contribution.

**Comment by gau-nernst** [comment]
I can't guarantee that the model trained here can be used in the original centernet repo, or any repo. I haven't extensively tested onnx export, so nothing is guaranteed, again.

For mAP calculation, this repo has a wrapper around pycocotools to provide multi-gpu support. Usage is like below

```python
from centernet_lightning.eval.coco import CocoEvaluator

evaluator = CocoEvaluator(num_classes)
for inputs, targets in val_dataloader:
    preds = model(inputs)    # for illustration purpose only. the actual model used in this repo is not called like this
    evaluator.update(preds, targets)    # update with a batch of predictions and targets
results = evaluator.get_metrics()    # dictionary of COCO metrics
```

You can check `validation_step()` and `validation_epoch_end()` to see how the evaluator is used.

You may want to use a more "tested" method to calculate mAP, such as directly use pycocotools. The [reference script](https://github.com/pytorch/vision/blob/main/references/detection/coco_eval.py) from torchvision also provides multi-GPU support for mAP calculation.

Note that this repo is not actively maintained by me. I recommend you to use other repos instead, such as YOLOv5 or torchvision (the new torchvision release includes FCOS, which is also an anchor-free detector but doesn't use the idea of "heatmap" like in CenterNet).

**Comment by javalier** [comment]
> 

thanks for your reply,Honestly, i am testing centernet now and i am not interest in other dectector，so thank you again for this repo.

**Comment by javalier** [comment]
there [https://github.com/gau-nernst/centernet-lightning/blob/main/centernet_lightning/models/__init__.py](url) write about backbone,but i can't find the backbone.py, i want to use my backbone（resnet+senet）how can i gei it done.

**Comment by gau-nernst** [comment]
as mentioned in #2, I started a refactoring work on this repo but never finished. The backbones were moved to a separate repo [gau-nernst/vision-toolbox](https://github.com/gau-nernst/vision-toolbox). To use a fully working repo before the refactoring, you should checkout commit d9682de11.
